// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/facts": {
            "get": {
                "description": "Fetch all facts data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facts"
                ],
                "summary": "ListFacts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search question",
                        "name": "question",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Create new fact data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facts"
                ],
                "summary": "CreateFacts",
                "parameters": [
                    {
                        "description": "Fact object to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateFactPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/requests.CreateFactPayload"
                        }
                    },
                    "400": {
                        "description": "Error parsing body payload"
                    }
                }
            }
        },
        "/facts/{id}": {
            "get": {
                "description": "Fetch fact data by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facts"
                ],
                "summary": "GetFactByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fact ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "ID is not a valid number"
                    },
                    "404": {
                        "description": "Data not found"
                    }
                }
            }
        }
    },
    "definitions": {
        "requests.CreateFactPayload": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "Answer x."
                },
                "question": {
                    "type": "string",
                    "example": "Question x?"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GO API Course",
	Description:      "GO API using Gin framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
